<a href="https://colab.research.google.com/github/sevinchoyazimboevna-source/ai_foundation/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd

In [ ]:
malumot = {
    'Ism': ['Angel', 'Arletti', 'Alex', 'Giovanna'],
    'Yosh': [20, 25, 30, 22],
    'Shahar': ['Toshkent', 'Samarqand', 'Buxoro', 'Toshkent'],
    'Maosh': [500, 800, 1200, 600]
}
df = pd.DataFrame(malumot)
print(df)

    Ism  Yosh     Shahar  Maosh
0   Ali    20   Toshkent    500
1  Vali    25  Samarqand    800
2  Sami    30     Buxoro   1200
3  Guli    22   Toshkent    600

In [ ]:
df.head(2)

    Ism  Yosh     Shahar  Maosh
0   Ali    20   Toshkent    500
1  Vali    25  Samarqand    800

In [ ]:
df.tail(2)

    Ism  Yosh    Shahar  Maosh
2  Sami    30    Buxoro   1200
3  Guli    22  Toshkent    600

In [ ]:
df.shape

(4, 4)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Ism     4 non-null      object
 1   Yosh    4 non-null      int64
 2   Shahar  4 non-null      object
 3   Maosh   4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

In [ ]:
df.describe()

            Yosh        Maosh
count   4.000000     4.000000
mean   24.250000   775.000000
std     4.349329   309.569594
min    20.000000   500.000000
25%    21.500000   575.000000
50%    23.500000   700.000000
75%    26.250000   900.000000
max    30.000000  1200.000000

In [ ]:
df = pd.DataFrame({
    'Ism': ['Ali', 'Vali', 'Sami', 'Guli'],
    'Yosh': [20, 25, 30, 22],
    'Maosh': [500, 800, 1200, 600]
})
print(df)

    Ism  Yosh  Maosh
0   Ali    20    500
1  Vali    25    800
2  Sami    30   1200
3  Guli    22    600

In [ ]:
print(df.loc[1:,"Ism"])

1    Vali
2    Sami
3    Guli
Name: Ism, dtype: object

In [ ]:
print(df.iloc[0:2])

    Ism  Yosh  Maosh
0   Ali    20    500
1  Vali    25    800

In [ ]:
print(df.iloc[0:2, 0:2])

    Ism  Yosh
0   Ali    20
1  Vali    25

In [ ]:
df[df["Yosh"]>22]

    Ism  Yosh  Maosh
1  Vali    25    800
2  Sami    30   1200

In [ ]:
df[df["Ism"]=="Sami"]

    Ism  Yosh  Maosh
2  Sami    30   1200

In [ ]:
df.sum()

Ism      AliValiSamiGuli
Yosh                  97
Maosh               3100
dtype: object

In [ ]:
df.sum(numeric_only=True)

Yosh       97
Maosh    3100
dtype: int64

In [ ]:
df.count()

Ism      4
Yosh     4
Maosh    4
dtype: int64

In [ ]:
df = pd.DataFrame({
    'Ism': ['Ali', 'Vali', 'Sami', 'Guli'],
    'Yosh': [20, None, 30, 22],
    'Maosh': [500, 800, None, 600]
})
df

    Ism  Yosh  Maosh
0   Ali  20.0  500.0
1  Vali   NaN  800.0
2  Sami  30.0    NaN
3  Guli  22.0  600.0

In [ ]:
df.isnull().sum()

Ism      0
Yosh     1
Maosh    1
dtype: int64

In [ ]:
df.dropna(subset=['Yosh'])

    Ism  Yosh  Maosh
0   Ali  20.0  500.0
2  Sami  30.0    NaN
3  Guli  22.0  600.0

In [ ]:
df.fillna({"Yosh":1, "Maosh":0})

    Ism  Yosh  Maosh
0   Ali  20.0  500.0
1  Vali   1.0  800.0
2  Sami  30.0    0.0
3  Guli  22.0  600.0

In [10]:
df = pd.read_csv("Titanic-Dataset.csv")
df.head(100)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,0,3,"Shorney, Mr. Charles Joseph",male,NaN,0,0,374910,8.0500,NaN,S
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
97,98,1,1,"Greenfield, Mr. William Bertram",male,23.0,0,1,PC 17759,63.3583,D10 D12,C
98,99,1,2,"Doling, Mrs. John T (Ada Julia Bone)",female,34.0,0,1,231919,23.0000,NaN,S
99,100,0,2,"Kantor, Mr. Sinai",male,34.0,1,0,244367,26.0000,NaN,S

In [11]:
df.to_excel("output.xlsx")

In [12]:
# Series => 1D
cars = pd.Series(["Porsche", "Range Rover"])
print(cars)

0        Porsche
1    Range Rover
dtype: object